### ISSUE TITLE
Is there any convenient way that I can color my own generated character model?

### ISSUE THREAD

**Issue by Gloria-xhy** [marcopesavento/Super-resolution-3D-Human-Shape-from-a-Single-Low-Resolution-Image#3]
Thanks for your apealling work,sir.The character model being generated has beyond my preliminary imagination.It certainly will be way more better if I am capable of coloring it.
**So I wanna ask that is there any convenient way that I can color my own generated character model or get the model texture and apply to it?**I would be very grateful if you could answer.Thanks

**Comment by marcopesavento** [comment]
Hi, unfortunately we haven't implemented any convenient way to generate texture for the reconstructed mesh and we are exploring this as a future work. 
A naive approach you could use to create colors is to project the 3D points of the space in the 2D image and save the obj file with the RGB values of the pixel corresponding to the projected 3D point. However, this approach works fine only for the points that are visible in the 2D image and would just repeat the colors for the points that are not visible.

**Comment by Gloria-xhy** [comment]
Thanks for your reply!
